name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm install
      - name: "Generate SBOM"
        uses: anchore/sbom-action@v0
        with:
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'
      - name: "Build site"
        run: npm run build
      - name: "Package the build"
        run: tar -czf dist.tar.gz dist
      # Commented out, as the SBOM version includes more detail.
      # - name: Attest Build Provenance
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: "dist.tar.gz"
      - uses: actions/attest-sbom@v1
        with:
          subject-path: 'dist.tar.gz'
          sbom-path: 'sbom.spdx.json'
      - name: "Publish the SBOM"
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
      - name: "Publish the build"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.tar.gz
      

  # Deploy job
  # deploy:
  #  # Add a dependency to the build job
  #  needs: build

  #  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #  permissions:
  #    pages: write      # to deploy to Pages
  #    id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
  #  environment:
  #    url: ${{ steps.deployment.outputs.page_url }}
  #    name: github-pages

    # Specify runner + deployment step
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
